
import streamlit as st
import os


# Check if user is logged in
if "user" not in st.session_state:
    st.error("You must log in first!")
    st.session_state["page"] = "login"
    

# ----------------------------------------------------
# Below is your existing dashboard code, adapted:
# ----------------------------------------------------

# If "uploaded_files" not in session, init
if "uploaded_files" not in st.session_state:
    st.session_state.uploaded_files = []  # Store file names or paths

# Sidebar: Uploaded Files
st.sidebar.title("Uploaded Files")
st.sidebar.write("Here is a pile of files you've uploaded in the past:")

if st.session_state.uploaded_files:
    for i, file in enumerate(st.session_state.uploaded_files):
        st.sidebar.write(f"{i+1}. {file}")
else:
    st.sidebar.write("No files uploaded yet.")

# File Upload Section
st.sidebar.write("---")
uploaded_file = st.sidebar.file_uploader("Upload a file (PDF or Text)", type=["pdf", "txt"])

if uploaded_file:
    file_name = uploaded_file.name
    # Save the file locally
    with open(os.path.join("uploads", file_name), "wb") as f:
        f.write(uploaded_file.getbuffer())
    st.session_state.uploaded_files.append(file_name)
    st.sidebar.success(f"{file_name} uploaded successfully!")

# Main Dashboard Content
st.title("Dashboard")
st.write("Upload and manage your files. Summarize text or perform Q&A on the uploaded content.")

# Display Uploaded Files in a Table
if st.session_state.uploaded_files:
    st.subheader("Uploaded Files")
    for file_name in st.session_state.uploaded_files:
        st.write(f"📄 **{file_name}**")
else:
    st.info("No files available. Start by uploading a file!")

# Placeholder for Summarization and Q&A
st.write("---")
st.subheader("Summarization and Q&A")
st.write("This section will display summaries or answers generated by the integrated ML model.")
st.warning("Model integration coming soon!")

# (Optional) Logout button
if st.button("Logout"):
    st.session_state.pop("user", None)
    st.session_state["page"] = "home"

